changes in deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -39,6 +39,19 @@ jobs:
             ${{ secrets.EC2_SSH_KEY }}
 
           script: |
+          # ✅ Install Docker if not installed
+            if ! command -v docker &> /dev/null
+            then
+                echo "Docker not found! Installing Docker..."
+                sudo apt update -y
+                sudo apt install -y docker.io
+                sudo systemctl start docker
+                sudo systemctl enable docker
+                sudo usermod -aG docker $USER
+            else
+                echo "Docker is already installed."
+            fi
+            
             sudo docker stop todo-backend || true
             sudo docker rm todo-backend || true
             sudo docker pull ${{ secrets.AWS_ECR_URI }}/todo-backend:latest
